version: '3.3'
services:
  web:
    image: 'jormae/bacho-hrms-web:1.0.13'
    build: .
    ports:
      - 8005:3005
    restart: always
    #left -> local, right ->container
    #http://lcoalhost:8080 -p 8080:3000
